Log for creating 3D model tile(s) for  NED_-105.07_36.52 
 
DEM_name = USGS/NED 
trlat = 36.692603270926334 
trlon = -104.90138908691407 
bllat = 36.34605749573734 
bllon = -105.23441215820313 
printres = 0.2 
ntilesx = 1 
ntilesy = 1 
tilewidth = 100.0 
basethick = 2 
zscale = 1.5 
fileformat = STLb 
no_bottom = False 
unprojected = False 
no_normals = True 

process started: 02:40:19.995126 

Region (lat/lon):
   36.692603270926334 -104.90138908691407 (top right)
   36.34605749573734 -105.23441215820313 (bottom left) 
center at [-105.0679006225586, 36.519330383331834]  UTM 13 N ,  EPSG:32613 
lon/lat size in degrees: [0.3330230712890625, 0.3465457751889929] 
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 42, in autodetect
    from . import file_cache
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 42, in autodetect
    from . import file_cache
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Earth Engine raster: USGS/NED 
 USGS National Elevation Dataset 1/3 arc-second 
URL for geotiff is:  https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/thumbnails/653ac07d762154e350a16f983eebdd42-d5662808d41f80109d9e3623b0f51295:getPixels 
 geotiff size: 1.02191162109375 Mb 
 cell size 59.65695010786502 m, upper left corner (x/y):  478925.9954659404 4060848.593842372 
full (untiled) raster (height,width):  (646, 502) float64 
cell size: 59.65695010786502 m  
adjusted print res from the requested 0.2 mm to 0.199203187250996 mm to ensure correct model dimensions 
total model size in mm: 100.0 x 128.68525896414343 
map scale is 1 : 299477.8895414824 
Cells per tile (x/y) 502 x 646 
using single-core only 

1 x 1 tiles, tile size 100.00 x 128.69 mm
 
tile 1 1 : height:  2.0 - 15.870193931878337 mm , file size: 62 Mb 

total size for all tiles: 62 Mb 
added full geotiff as NED_-105.07_36.52.tif 

processing finished: 02:40:41.437157 
